services:
  php-sistema:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
    networks:
      - rabbitmq_network # Conecta o sistema à mesma rede do rabbitmq(broker de mensagens)
    environment:
      # Variável de ambiente para o script PHP usar
      # O valor é o "container_name" definido no docker-compose.yaml do rabbitmq
      RABBITMQ_HOST: rabbitmq

  db:
    image: mysql
    restart: always
    ports:
      - 9306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1

networks:
  rabbitmq_network:
    external: true